### ISSUE TITLE
Left-side Navigation Bar

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#13]
<img width="216" alt="Screenshot 2020-10-29 at 14 29 45" src="https://user-images.githubusercontent.com/26879042/97580131-37de6080-19f3-11eb-9318-15b271ad216f.png">
**Side Menu Drawer** 

Side Menu Drawer Element which opens on Prifina Icon

**Includes: Icons, Labels, Back Home Button**

**Relevant user story:** [User story](https://docs.google.com/document/d/1DStWC9_QuyFYZf0j0dXbdD5xrebMU4a8HM-Htw95Gm4/edit#)

**Visual component design:** [Figma file](https://www.figma.com/file/9z7bqVLQmFmas2OsNUIAn6/Prifina-Core-Navigation-(Copy)?node-id=957%3A4044)

**Specifications:**

**Comment by mmlampinen** [comment]
hi @hamzahalilovic - it looks like this user story link is incorrect, here is the correct one: https://docs.google.com/document/d/12GXNUdyK75S2Kdvh-wN2kQ6SBNJj5bIZpWDn-8Xkc6s/edit

Also in that user story, you can note that the 0.24 milestone has only 3 UIs, so it has no left side navigation at all (or other broader navigation than those 3 UIs)

**Comment by hamzahalilovic** [comment]
@mmlampinen - I think this is the correct one, it says "A1.1.F1U17 As a new user, I want to access my navigation at all times" (https://docs.google.com/document/d/1DStWC9_QuyFYZf0j0dXbdD5xrebMU4a8HM-Htw95Gm4/edit#) in which user accesses navigation on Prifina Icon

**Comment by mmlampinen** [comment]
@hamzahalilovic Yes, looks correct!

**Comment by valto** [comment]
@hamzahalilovic actually this A1.1.F1U17 is for user menu (note: right side). But it's just so old that term did not exist yet.
