### ISSUE TITLE
Left-side Navigation Bar Link

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#14]
<img width="216" alt="Screenshot 2020-10-29 at 14 29 45" src="https://user-images.githubusercontent.com/26879042/97580194-488ed680-19f3-11eb-919c-5529c8d27e83.png">
Side Menu Drawer Back To Home Button

**Includes:** Button with text and icon

**Relevant user story:** [User story](https://docs.google.com/document/d/1DStWC9_QuyFYZf0j0dXbdD5xrebMU4a8HM-Htw95Gm4/edit#)

**Visual component design:** [Figma file](https://www.figma.com/file/9z7bqVLQmFmas2OsNUIAn6/Prifina-Core-Navigation-(Copy)?node-id=957%3A4044)

**Specifications:**

**Comment by mmlampinen** [comment]
@hamzahalilovic See previous comment, I believe this is 0.44
