### ISSUE TITLE
User Menu

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#16]
<img width="204" alt="Screenshot 2020-10-29 at 14 32 51" src="https://user-images.githubusercontent.com/26879042/97580484-a8857d00-19f3-11eb-951f-9e1be71c4cc0.png">

**Profile Side Menu Drawer Element**

From User menu user can navigate to:
Notifications
Previous applications
Back to home screen
Logout

**Includes:** Notification Card, User Menu Icons (Home, Recent, Logout, Notifications), Profile Avatar

**Relevant user story:** [User Story](https://docs.google.com/document/d/1-21eL8ZVlGxLLcVfTu8LE61wpdbq7rE7WzUQK6pr07w/edit#)

**Visual component design:** [Figma file](https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=1935%3A14321)

**Specifications:**

**Comment by valto** [comment]
@hamzahalilovic We have been calling this as "user menu" in some other contexts.

**Comment by prifina-admin** [comment]
Assigning to @tro9999 as discussed separately, due to other current priorities
