### ISSUE TITLE
Profile Icon in User Menu

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#17]
<img width="600" alt="Screenshot 2020-10-29 at 14 35 13" src="https://user-images.githubusercontent.com/26879042/97580729-fc906180-19f3-11eb-8bde-22296f3481f5.png">
**Profile Icon in Profile Side Menu Drawer**

Profile Icon in Profile Side Menu Drawer

**Includes:** 

**Relevant user story:** [User story](https://docs.google.com/document/d/1S-nt6BL5P5R32AP6bq3YiL-J8A0dLKkkc1x5qhp0GEs/edit#heading=h.o6do42inilxx)

**Visual component design:** [Figma file](https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=1895%3A1911)

**Specifications:**

**Comment by valto** [comment]
@hamzahalilovic Let's rename to Avatar icon as that's a term been used in some other contexts.
