### ISSUE TITLE
Personal Cloud Service Option Box

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#19]
<img width="249" alt="Screenshot 2020-11-03 at 00 41 06" src="https://user-images.githubusercontent.com/26879042/97931284-8f6f2a00-1d6d-11eb-875f-b8065affb6e5.png">

**Personal Cloud Service Container**

Personal Cloud Service Container to be presented to the user on “Select Your Personal Cloud Service" -page, that is shown to the user after the registration User Story, where user is presented, and where user can compare provided cloud service options

**Includes:** "Select Button", Text Labels

**Relevant user story:** [User story](https://docs.google.com/document/d/148Oh7AnmXeJ-IBpVWqSGH7jgRo9wNLOjXBnUXeJ9tvg/edit?ts=5f87335e#)

**Visual component design:** [Figma file](https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=1997%3A12)

**Specifications:**

**Comment by prifina-admin** [comment]
Included in #56
