### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#21]
<img width="647" alt="Screenshot 2020-10-29 at 14 38 54" src="https://user-images.githubusercontent.com/26879042/97581178-8c361000-19f4-11eb-9468-f412afa9a926.png">

**Home Page**

Home page of the Prifina web app

**Includes:** Prifina Logo, Navigation Cards, Search Icon, Avatar Icon

**Relevant user story:** [https://docs.google.com/document/d/12GXNUdyK75S2Kdvh-wN2kQ6SBNJj5bIZpWDn-8Xkc6s/edit](url)
**Visual component design:** [https://www.figma.com/file/9z7bqVLQmFmas2OsNUIAn6/Prifina-Core-Navigation-(Copy)?node-id=957%3A4044](url)

**Specifications:**

**Comment by mmlampinen** [comment]
@hamzahalilovic Link and screenshot should be updated. Here's the relevant design https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=1895%3A1523
