### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#31]
**Progress Bar**

There is an anchored progress that allows the user to see the file upload process (e.g. duration, how much of the file has uploaded). During this upload the user can continue to do other tasks and return to this progress bar.

**Includes:** Progress bar

**Relevant user story:** [https://docs.google.com/document/d/12GXNUdyK75S2Kdvh-wN2kQ6SBNJj5bIZpWDn-8Xkc6s/edit](url)
**Visual component design:** [https://www.figma.com/file/9z7bqVLQmFmas2OsNUIAn6/Prifina-Core-Navigation-(Copy)?node-id=957%3A4044](url)

**Specifications:**

**Comment by mmlampinen** [comment]
@hamzahalilovic is this link correct? Looks like it goes to the app market view. Btw, if you select the "text above" the figma screen, then you can get the link to go directly there: https://www.figma.com/file/9z7bqVLQmFmas2OsNUIAn6/Prifina-Core-Navigation-(Copy)?node-id=965%3A1406

**Comment by hamzahalilovic** [comment]
@mmlampinen Great, didn't know that. Figma file wasn't included in the document so I used the one where I could find Console app
