### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#51]
<img width="633" alt="Screenshot 2020-11-03 at 01 56 22" src="https://user-images.githubusercontent.com/26879042/97935067-cfd3a580-1d77-11eb-9d5e-fe9ce4fbd7d6.png">

**Home Page** 

Users Story Task Flow (also known as User Journey)
1. User enters home screen with ‘pre installed apps’ and ‘user menu’
2. User chooses where they will navigate next 

**Includes:** "Pre-installed" App icons and "User Menu"
 

**Relevant user story:** [User Story](https://docs.google.com/document/d/1-21eL8ZVlGxLLcVfTu8LE61wpdbq7rE7WzUQK6pr07w/edit#)

**Visual component design:** [Figma file](https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=1935%3A14321)

**Specifications:**

**Comment by prifina-admin** [comment]
Assigning to @tro9999 as discussed, given dependencies to other work
