### ISSUE TITLE
User Icon

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#53]
<img width="360" alt="Screenshot 2020-11-03 at 01 59 02" src="https://user-images.githubusercontent.com/26879042/97935208-2f31b580-1d78-11eb-98be-4da615bb2d84.png">

**User Menu Icon** 

User menu icons (Home, Recent, Sign out, Notifications)

**Includes:** 
 

**Relevant user story:** [User Story](https://docs.google.com/document/d/1-21eL8ZVlGxLLcVfTu8LE61wpdbq7rE7WzUQK6pr07w/edit#)

**Visual component design:** [Figma file](https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=1935%3A14321)

**Specifications:**

**Comment by prifina-admin** [comment]
This is not one icon... instead part of usermenu
