### ISSUE TITLE
Left-side Navigation Bar Icon

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#55]
<img width="216" alt="Screenshot 2020-10-29 at 14 29 45" src="https://user-images.githubusercontent.com/26879042/97580248-57758900-19f3-11eb-83ec-64180bd2e99b.png">
**Left-side Navigation Bar Icon**

Left-side Navigation Bar icons : Prifina, Dashboard, Cloud, Search

**Includes:** 

**Relevant user story:** [User story](https://docs.google.com/document/d/1DStWC9_QuyFYZf0j0dXbdD5xrebMU4a8HM-Htw95Gm4/edit#)

**Visual component design:** [Figma file](https://www.figma.com/file/9z7bqVLQmFmas2OsNUIAn6/Prifina-Core-Navigation-(Copy)?node-id=957%3A4044)

**Specifications:**

**Comment by mmlampinen** [comment]
@hamzahalilovic Question. How did you classify this in 0.21? I believe this is first in the data console user stories (not the "upload file" flow), so it is 0.44, correct?

**Comment by hamzahalilovic** [comment]
@mmlampinen This was taken out of "I want to access my navigation at all times" story, but the story doesn't have a flow so I put this navigation menu also. I can transfer it to one of the stories in 0.44 where it's used.

**Comment by mmlampinen** [comment]
Understood. I think that user story is covered by the "user menu" which is in 0.21. Let's transfer this one to 0.44 with the other data console flows

**Comment by hamzahalilovic** [comment]
Sure :)
