### ISSUE TITLE
Left Side Bar

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#65]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![Uploading Screen Shot 2020-11-04 at 3.45.25 AM.png…]()

**Comment by serg-coder** [comment]
![left-side-bar](https://user-images.githubusercontent.com/62238127/98056432-06312380-1e51-11eb-8ad1-6cff31c173a1.png)
