### ISSUE TITLE
Left Child Side Bar

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#66]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![left child side bar](https://user-images.githubusercontent.com/62238127/98056399-eb5eaf00-1e50-11eb-9bdf-c3e41d43fe5b.png)
