### ISSUE TITLE
Right Selection Tab View

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#67]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![tab-view](https://user-images.githubusercontent.com/62238127/98056580-4a242880-1e51-11eb-9391-a37d1e75a80a.png)
