### ISSUE TITLE
Select Box(Dropdown)

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#68]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![dropbox](https://user-images.githubusercontent.com/62238127/98056617-6922ba80-1e51-11eb-9147-6ba1cad7e766.png)
