### ISSUE TITLE
Search InputBox

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#69]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![search-box](https://user-images.githubusercontent.com/62238127/98056656-822b6b80-1e51-11eb-8aff-183af5418322.png)
