### ISSUE TITLE
Password Reset Page

### ISSUE THREAD

**Issue by AngelEngineer314** [prifina/app-desktop#7]
Password Reset React Page

Create Password Reset React Page

This is a page for user password reset.
This includes five form components with username, email, email verification, password reset, reset confirm components.
Each components were built with React function using React material UI.

Includes Components: Email.js / VerificationEmail.js / NewPassword.js / ResetConfirm.js / ResetDescription.js

Storybook draft documentation: https://docs.google.com/document/d/1LYFpVsRkH5VCHaCqYnYTzr0swspxngJaQov4qQTbYOg/edit

Visual component design: "Password Reset"
https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=869%3A0

**Comment by valto** [comment]
Thanks @venusworld314 - @tro9999 will check this and will give you details for whats next.

**Comment by valto** [comment]
@venusworld314 What do you mean by 'Material UI'? As we are not using that. But our own existing components. And if not available, developing our own.

**Comment by venusworld314** [comment]
React Material UI design

**Comment by valto** [comment]
@tro9999 - adding here a file from the component shared by @venusworld314 [reset-password_20-10-21 (1).zip](https://github.com/prifina/app-desktop/files/5438994/reset-password_20-10-21.1.zip)

**Comment by prifina-admin** [comment]
@venusworld314 Component extraction from design is good. Naming is bit too short and general, like Email.js, as it is not "field" component, it could have longer name, like ResetUsingEmail.js 

- I see you already started developing, but it was bit too early. As this is part of larger app, it should fit with overall structure and using only existing node modules. In good reason, new modules is possible to add, but as general rule package.json changes are not allowed. 
- I recommend you have a look a alpha branch and you can see, how those components, that are marked existing, looks like. 
There are storybook setup ready, so it is best way to see those. 
- You can also see that we are using our own design system (blend-ui), which is heavily depended on using styled-components principle. As you are already familiar with Material-ui, it has some similarities as they have started to use the same. 
- Normal development workflow requires forking and then creating pull request agains alpha branch. Also required are working storybook story for separate visual checking (not required to integrate with App routing) and Jest testing script for automated testing. Currently there are no existing jest tests (my bad), but basic rendering test using "react-test-renderer" is very simple. 
- If development has any new reusable functions (not component), then it is necessary to include jest test for testing.
