### ISSUE TITLE
Table View

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#70]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![tableview](https://user-images.githubusercontent.com/62238127/98056688-966f6880-1e51-11eb-87a6-77a36124afe6.png)
