### ISSUE TITLE
App Button Color

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#71]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![colorbutton](https://user-images.githubusercontent.com/62238127/98056745-b2730a00-1e51-11eb-8d28-f64f22e8468a.png)
