### ISSUE TITLE
Left Side Complete Section

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#72]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![leftside](https://user-images.githubusercontent.com/62238127/98056780-c9196100-1e51-11eb-8111-3124f31d9e42.png)
