### ISSUE TITLE
Right Side Complete Section

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#73]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![rightsidebar](https://user-images.githubusercontent.com/62238127/98056819-e64e2f80-1e51-11eb-81d3-6bbb74994ebb.png)
