### ISSUE TITLE
Combine(Left Sidebar, Right Section)

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#74]
Page Name: Console UI concept(1)  (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A850)

**Comment by serg-coder** [comment]
![dashboard-combination](https://user-images.githubusercontent.com/62238127/98056883-0978df00-1e52-11eb-95f4-b74e3360a0be.png)
