### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#75]
Page Name : Dashboard UI Concept (1) (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A700)

**Comment by serg-coder** [comment]
![header](https://user-images.githubusercontent.com/62238127/98056935-2ad9cb00-1e52-11eb-9257-a590af4d3609.png)
