### ISSUE TITLE
Center Div for Search Box

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#76]
Page Name : Dashboard UI Concept (1) (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A700)

**Comment by serg-coder** [comment]
![center-div-searchbox](https://user-images.githubusercontent.com/62238127/98057024-5361c500-1e52-11eb-8bc1-7a122b3c668f.png)
