### ISSUE TITLE
Browse Apps Back Link

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#77]
Page Name : Dashboard UI Concept (1) (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A700)

**Comment by serg-coder** [comment]
![browseapps-back](https://user-images.githubusercontent.com/62238127/98057061-6aa0b280-1e52-11eb-8723-8962325b3e61.png)
