### ISSUE TITLE
Heading Label

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#80]
Page Name : Dashboard UI Concept (1) (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A700)

**Comment by serg-coder** [comment]
![heading-label](https://user-images.githubusercontent.com/62238127/98057292-02060580-1e53-11eb-8e54-1603dbfc2edf.png)
