### ISSUE TITLE
Title and Description Section

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#81]
Page Name : Dashboard UI Concept (1) (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A700)

**Comment by serg-coder** [comment]
![description](https://user-images.githubusercontent.com/62238127/98057347-1fd36a80-1e53-11eb-82b2-1022cbc0d613.png)
