### ISSUE TITLE
App Information Table

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#82]
Page Name : Dashboard UI Concept (1) (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A700)

**Comment by serg-coder** [comment]
![information-list](https://user-images.githubusercontent.com/62238127/98057374-32e63a80-1e53-11eb-8608-9fbc994f8e47.png)
