### ISSUE TITLE
App Details Left Sidebar

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#83]
Page Name : Dashboard UI Concept (1) (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A700)

**Comment by serg-coder** [comment]
![left-bar](https://user-images.githubusercontent.com/62238127/98057416-4abdbe80-1e53-11eb-9889-b50f0c3f6dea.png)
