### ISSUE TITLE
App Details Right Section

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#84]
Page Name : Dashboard UI Concept (1) (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A700)

**Comment by serg-coder** [comment]
![rightbar](https://user-images.githubusercontent.com/62238127/98057452-645f0600-1e53-11eb-9174-3908764e7d53.png)
