### ISSUE TITLE
App Details Combine (Left Sidebar, Right Section & Header)

### ISSUE THREAD

**Issue by jobinse** [prifina/app-desktop#85]
Page Name : Dashboard UI Concept (1) (https://www.figma.com/file/liwrg2buYcx1qeBVNuxfQh/Prifina-UI-ReStyle-(Copy)?node-id=183%3A700)

**Comment by serg-coder** [comment]
![app-directory-page](https://user-images.githubusercontent.com/62238127/98057505-80fb3e00-1e53-11eb-8c4d-309f3871657f.png)
