### ISSUE TITLE
Prifina Logo

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/app-desktop#9]
<img width="74" alt="Screenshot 2020-10-29 at 14 22 08" src="https://user-images.githubusercontent.com/26879042/97579553-7a536d80-19f2-11eb-9017-8499d944281e.png">

**Prifina Logo Component**

**Prifina logo** 

**Includes:** Prifina Logo

**Relevant user story:** [User Story](https://docs.google.com/document/d/1-21eL8ZVlGxLLcVfTu8LE61wpdbq7rE7WzUQK6pr07w/edit#)

**Visual component design:** [Figma file](https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=1935%3A14321)

**Specifications:**

**Comment by mmlampinen** [comment]
@hamzahalilovic - let's review all these, where we can check that they already exist in storybook, e.g. this one we can see here: http://alpha.app-storybook.prifina.com/?path=/story/container--container 

So this should then be marked into "Done" in the component project board
